### ISSUE TITLE
서버 세팅

### ISSUE THREAD

**Issue by dragonist** [bong-dragon/cowlib-front#11]
1. 아마존 회원가입
2. mysql, java8, nodejs 설치
3. git clone cowlib-server -> gradle build -> java -jar ./build/lib/cowlib-server
4. git clone cowlib-front -> npm install ... (README.md 참고)
5. 도메인 신청 연결

**Comment by underlinee** [comment]
1,2,3,4 까지 완료!

front랑 서버 연동하는거 해야함

- aws 8080 포트는 함부로 접속할 수 없음
```
./gradlew build -x test
java -jar ./build/libs/cowlib-server.jar --spring.profiles.active={{mode}}
```

**Comment by underlinee** [comment]
도메인 신청만 새 이슈로 남기고 이슈 close
