### ISSUE TITLE
더보기 버그

### ISSUE THREAD

**Issue by underlinee** [bong-dragon/cowlib-front#4]
검색결과의 숫자가 작은 경우 같은 결과가 반복됨

**Comment by underlinee** [comment]
daum book api 의 경우 pageNo가 1일때 결과가 요청한 결과 이하라도
2로 호출했을때 1의 결과를 준다...

**Comment by underlinee** [comment]
https://github.com/bong-dragon/cowlib-server/pull/34

**Comment by dragonist** [comment]
merge 완료되서 이슈를 종료합니다.
